### ISSUE TITLE
Develop a fully-featured WASM-to-native-application complier, to run web apps as normal applications.

### ISSUE THREAD

**Issue by Evi1M4chine** [WebAssembly/wasm-to-llvm-prototype#34]
The title says it all. :)

This would be ideal to do away with the inner-platform effect inherent to running apps in the browser, which itself is an app running in the OS. (A bad anti-pattern.)

As a bonus, the browser could finally be a document browser again.

**Comment by jcbeyler** [comment]
I'm not sure I understand this issue #. I agree with the idea though I think it is not automatically following the trend of current browsers. However, I find this a bit too big of an issue to be here like that. We could divide this into sub-issues and map out what we need.
- Full coverage of the Wasm language
- Generating the code directly into a stand-alone module

come to mind but we would want more details I think than just this generic issue...

**Comment by jcbeyler** [comment]
Closing now, this is a reach goal that does not seem to be the scope of this prototype for now :)

**Comment by Evi1M4chine** [comment]
Understood.

*sheds a single tear*

(The whole point of my post was to not follow the cancerous and [utterly idiotic](https://en.wikipedia.org/wiki/Inner-platform_effect) trend of the current browsers, and enabling people to get rid of the wasteful and pointless inner-platform layer. As a nice side-effect, browsers become actual document browsers again. [Something I’m then tackling and will get rid of, together with the whole anti-collaborative/-modular “application” and invalid “desktop” concepts, with my own project.])
